name: publish

on: [push]

jobs:

  publish-hello-docker-image:

    runs-on: windows-latest

    steps:  
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry

      uses: docker/login-action@v1

      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    - name: Build the hello-docker Docker image

      run: |

            docker pull mcr.microsoft.com/dotnet/samples:aspnetapp-nanoserver-ltsc2022

            docker tag mcr.microsoft.com/dotnet/samples:aspnetapp-nanoserver-ltsc2022:latest ghcr.io/tanish-593/hello-docker-gcr-demo:latest

            docker push ghcr.io/tanish-593/hello-docker-gcr-demo:latest



